### ISSUE TITLE
location of CSS for customization

### ISSUE THREAD

**Issue by NatthakornK** [Appsilon/semantic.dashboard#110]
I could not find the location of your **css** stylesheet for `Sematics UI` for customisation. Any suggestion on its path? I would like to adjust fonts and colouring.

**Comment by dokato** [comment]
Hi @NatthakornK, this problem is actually related more to `shiny.semantic` dependency. Currently all static Semantic UI files are stored on CDN and we do not support custom paths. But this is definitely something worth to add. I will add it as a feature request to `shiny.semantic`.

**Comment by dokato** [comment]
@NatthakornK Now if you specify option `shiny.custom.semantic` it should take css and js from custom location.
