### ISSUE TITLE
Change Font of box title and menu header

### ISSUE THREAD

**Issue by ardeeshany** [Appsilon/semantic.dashboard#118]
Hi,
Thanks for the great package. I was wondering if we can change the font-family of box title and also the "menu" is written on top of the sidebar? It seems we cannot change them.

Thanks

**Comment by dokato** [comment]
Currently, you have to override CSS for those items to achieve that, but we might introduce more customization in the future.

**Comment by krystian8207** [comment]
You can get required effect by defining internal css style rules. For example to change font family for "Menu" and box headers replace https://github.com/Appsilon/semantic.dashboard/blob/develop/examples/sales/app.R#L8 with:
```
header <- dashboardHeader(
  tags$style("
             div.top.right.ribbon.label.blue {font-family: Arial, Helvetica, sans-serif !important;}
             #toggle_menu {font-family: Arial, Helvetica, sans-serif !important;}
             ")
  )
```
