### ISSUE TITLE
How to reduce space between ui element and page border or sidebar ?

### ISSUE THREAD

**Issue by bianchenhao** [Appsilon/semantic.dashboard#125]
I used example code, 
`
library(semantic.dashboard)
library(shiny)

ui <- dashboardPage(
    dashboardHeader(title = "Basic dashboard"),
    dashboardSidebar(sidebarMenu(
        menuItem(tabName = "home", text = "Home", icon = icon("home")),
        menuItem(tabName = "another", text = "Another Tab", icon = icon("heart"))
    )),
    dashboardBody(
        fluidRow(
            box(plotOutput("plot1", height = 250)),
            box(
                title = "Controls",
                sliderInput("slider", "Number of observations:", 1, 100, 50)
            )
        )
    )
)

server <- function(input, output) {
    set.seed(122)
    histdata <- rnorm(500)
    output$plot1 <- renderPlot({
        data <- histdata[seq_len(input$slider)]
        hist(data)
    })
}

shinyApp(ui, server)
`
![222](https://user-images.githubusercontent.com/40454528/60083461-592c9e00-9768-11e9-877f-6d3bd2b2ffa4.png)

Compared with shinydashboard, the space and margin are larger.

**Comment by dokato** [comment]
Hi @bianchenhao thanks for your questions. This can be adjusted in semantic CSS code.
For example, in `semantic.min.css` you may find `.ui.container` class and replace `margin-left` property with eg. 10px. I hope it helps!
