### ISSUE TITLE
Option to make sidebar and header `sticky`

### ISSUE THREAD

**Issue by maju116** [Appsilon/semantic.dashboard#13]
When scrolling down we want to have `dashboard_header` and `menu_item`s on sidebar always visible (sticky)

Example: https://www.w3schools.com/howto/howto_js_navbar_sticky.asp

**Comment by filipstachura** [comment]
Header is already sticky (used `fixed menu`): https://github.com/Appsilon/semantic.dashboard/tree/sticky-menu

We need to use a different approach for the sidebar.

**Comment by dokato** [comment]
Wit current approach to sidebar, this remark is no longer valid.
