### ISSUE TITLE
Adding style argument to dashboardSidebar doesnt work

### ISSUE THREAD

**Issue by pedrocoutinhosilva** [Appsilon/semantic.dashboard#134]
User defined styles can usually be added via the `style` argument, but in the case of dashboardSidebar using it will append the defined style but in a broken way:

For example:
```
  semantic.dashboard::dashboardSidebar(
    style = "padding: 10px;",
```

Will result in a broken state:
![Screenshot from 2019-12-09 12-26-45](https://user-images.githubusercontent.com/44022548/70432345-57893500-1a7f-11ea-969f-9d29ab988849.png)
![Screenshot from 2019-12-09 12-26-55](https://user-images.githubusercontent.com/44022548/70432346-5821cb80-1a7f-11ea-9040-4cfeab9de2ad.png)

Looks like a missing `;` should be added to the default styles created to prevent this at: https://github.com/Appsilon/semantic.dashboard/blob/6116687faec9c20a6fe789dd235c83d97f259eeb/R/semantic_dashboard.R#L121

**Comment by dokato** [comment]
#154 solves this issue.
