### ISSUE TITLE
BUGs: Theme argument doesn't work, sidebar color is ignored and date_input not found in the library

### ISSUE THREAD

**Issue by ponnet** [Appsilon/semantic.dashboard#135]
ui <- dashboardPage(
  dashboardHeader(
    headerPanel("Metrics")
),
  dashboardSidebar(
    color = "teal",
    sidebarMenu(
      date_input('startdate',
                label = 'Date input: yyyy-mm-dd',
                value = Sys.Date()
      )
    )
  ),
  ########## BODY
  dashboardBody( ),
  theme = "chubby"
)

**Comment by dokato** [comment]
thanks @ponnet for reporting this. Regarding the theme problem, indeed not all themes were copied yet from updated forest https://semantic-ui-forest.com/themes . We're working now on migrating from outdated semantic libraries to fomantic (look https://github.com/Appsilon/shiny.semantic/pull/147) that should solve date_input problem soon.

**Comment by dokato** [comment]
available themes are listed in `SUPPORTED_THEMES` vector
