### ISSUE TITLE
Disabling sidebar crashes the layout

### ISSUE THREAD

**Issue by dokato** [Appsilon/semantic.dashboard#137]
This is what happens:
![Screenshot 2020-01-24 at 15 12 45](https://user-images.githubusercontent.com/4547289/73079485-390abc00-3ebc-11ea-8b51-d447381d15e4.png)

when we have this

```r
dashboardSidebar(side = "left", size = "thin", color = "teal", disable = TRUE,
```
with `disable = FALSE` it works alright.

Probably realted to #33.

**Comment by drzamich** [comment]
I could not reproduce the issue in using the apps from `examples` directory using the code that's currently on the `develop` branch.
