### ISSUE TITLE
Would you have soon a new CRAN release?

### ISSUE THREAD

**Issue by AlexPars** [Appsilon/semantic.dashboard#138]
It was replied in shiny.semantic Github that there will be soon (1-2 weeks) a version 0.3.0 released on CRAN for shiny.semantic.

Since semantic.dashboard depends on shiny.semantic, would you also have a new CRAN release for semantic.dashboard?

**Comment by dokato** [comment]
Yeap, I'm finishing up revision of this PR: https://github.com/Appsilon/shiny.semantic/pull/151 . Once it's done, both packages should be CRANed up ;)

**Comment by AlexPars** [comment]
Thank you

**Comment by AlexPars** [comment]
I wanted to inquire whether you have any updated timeline for CRAN release of the new version of this R package

**Comment by rauniyar542** [comment]
Is the CRAN release of semantic dashboard package coming soon?

**Comment by dokato** [comment]
Hey @rauniyar542 , it should be released in upcoming week or two.

**Comment by dokato** [comment]
hi @AlexPars @rauniyar542 v `0.1.5` is on CRAN now: https://cran.r-project.org/web/packages/semantic.dashboard/index.html

**Comment by rauniyar542** [comment]
Do you have release notes? I'd like to understand what's new. Couldnt find it in github. Thanks.

Sent from Yahoo Mail on Android

**Comment by dokato** [comment]
See what's changed in shiny.semantic first https://github.com/Appsilon/shiny.semantic/blob/master/CHANGELOG.md
and here:
https://github.com/Appsilon/semantic.dashboard/blob/develop/CHANGELOG.md

We're going to work on dashboard more in the upcoming months, so expect new release towards the end of June.

**Comment by AlexPars** [comment]
Thank you for the info and the new CRAN release

**Comment by rauniyar542** [comment]
Hi,
I have a quick question. Is there a way I can click on an action button in one tab (say within dashboardBody of "Home" section in example below), that will take me to a specified table or chart in another tab (say within dashboardBody of "Another" section).
Thanks,Rahul
Note that the action button and chart/table is not specified in the example below.
#########################
library(shinydashboard) # <-- You only need to change this line to: library(semantic.dashboard)
#########################
ui <- dashboardPage(
  dashboardHeader(title = "Basic dashboard"),
  dashboardSidebar(sidebarMenu(
      menuItem(tabName = "home", text = "Home", icon = icon("home")),
      menuItem(tabName = "another", text = "Another Tab", icon = icon("heart"))
  )),
  dashboardBody(
    fluidRow(
      box(plotOutput("plot1", height = 250)),
      box(
        title = "Controls",
        sliderInput("slider", "Number of observations:", 1, 100, 50)
      )
    )
  )
)

server <- function(input, output) {
  set.seed(122)
  histdata <- rnorm(500)
  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })
}

shinyApp(ui, server)

    On Thursday, April 9, 2020, 11:49:11 AM EDT, dokato <notifications@github.com> wrote:  
 
 


See what's changed in shiny.semantic first https://github.com/Appsilon/shiny.semantic/blob/master/CHANGELOG.md
and here:
https://github.com/Appsilon/semantic.dashboard/blob/develop/CHANGELOG.md

We're going to work on dashboard more in the upcoming months, so expect new release towards the end of June.
