### ISSUE TITLE
Sidebar is scrolling together with the whole page

### ISSUE THREAD

**Issue by krystian8207** [Appsilon/semantic.dashboard#144]
The expected behavior is to have sidebar fixed. After a few tests I made, I'm pretty sure this is strongly related to #143.

**Comment by drzamich** [comment]
When working on the sidebar another thing should be fixed: now it's [height is fixed with inline style](https://github.com/Appsilon/semantic.dashboard/blob/develop/R/semantic_dashboard.R#L121) to `min-height: 100vh`. That's not really responsive.
