### ISSUE TITLE
ui.R: Error in dots_list(...) : 'nthcdr' needs a list to CDR down 

### ISSUE THREAD

**Issue by griipen** [Appsilon/semantic.dashboard#150]
I am in the process on merging my application from `shinydashboard` to `semantic.dashboard` and encounter an error when trying to launch any `semantic.dashboard` application. In essence, the problem arises in the UI definition.

**Code run (minimal semantic dashboard example):**
```
library(shiny)
library(semantic.dashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)

server <- shinyServer(function(input, output, session) {
})

shinyApp(ui, server)
```

The code breaks when defining the `ui` object with the following error. As a result, I am unable to launch the application as `ui` remains undefined.

`Error in dots_list(...) : 'nthcdr' needs a list to CDR down`

I am running `shiny 1.5.0` and `semantic.dashboard 0.1.8` on `R 3.4.4` / `Ubuntu 18.04`. Any ideas?

**Comment by dokato** [comment]
Hey @griipen . In semantic.dashboard, the dashboard elements content, can't be empty, eg.

```r
ui <- dashboardPage(
  dashboardHeader(p("abc")),
  dashboardSidebar(p("abc")),
  dashboardBody(p("abc"))
)

server <- function(input, output, session) {
}

shinyApp(ui, server)
```
