### ISSUE TITLE
dashboardSidebar side top or botton does not work

### ISSUE THREAD

**Issue by lukuiR** [Appsilon/semantic.dashboard#159]
I may do somethings wrong but even in your example dashboard when you change side to botton or top, menu does not show up at all.
how this can be fixed?

**Comment by dokato** [comment]
Thank you @lukuiR for reporting that. I'm trying to fix that in #161. I struggle a bit how to make it pushable, but works already when covering is not a problem (or you can increase padding of your top element).
<img width="302" alt="Screenshot 2021-03-05 at 14 37 03" src="https://user-images.githubusercontent.com/4547289/110130251-b80d3c00-7dc0-11eb-9bd6-c142a8da751e.png">
