### ISSUE TITLE
Timeline for next CRAN release for this package?

### ISSUE THREAD

**Issue by AlexPars** [Appsilon/semantic.dashboard#202]
Since last CRAN release for this package was in 2021, would you have a timeline for next CRAN release?

Two more inquiries, please:

1. Would you recommend using shiny.semantic and semantic.dashboard within a framework built with your excellent rhino package?
2. Given that you have released recently other packages for dashboard creation, would you recommend any of the other packages over this one, in terms of current and future functionalities?

**Comment by osenan** [comment]
Hi!
We are developing a new version for semantic.dashboard. Our plan is to release in 2023, but I cannot provide more specific details at this point. You can see in here https://github.com/Appsilon/semantic.dashboard/issues/183 what is being developed.
shiny.semantic and semantic.dashboard work perfectly with rhino! Rhino will provide a pre build framework to develop the application. It will speed up your development while helping you adopting software development best practices.
If you are more proficient with shiny.semantic and semantic.dashboard, or they are more suitable for your project there is no specific recommendation to switch to another ui package! Our goal to develop other packages, like shiny.fluent is to offer more possibilities, to adapt to more projects, developers, to bring more front end libraries and technologies to Shiny so in the end Shiny remains a great tool for developing dashboards.
