### ISSUE TITLE
Convert Crandash example to Semantic.dashboard

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/semantic.dashboard#27]
Convert this example:
https://github.com/rstudio/shiny-examples/tree/b281a0a78c2481b6e506ffcb27eb431aefdcf575/087-crandash

# Acceptance criteria:
- Complete dashboard code works with semantic.dashboard instead of shiny.dashboard, except for:
   - TODO @maju116 add complete list of differences

**Comment by maju116** [comment]
Differences in `ui.R` between `semantic.dashboard` and `shinydashboard` :

1. In `semantic.dashboard` title is passed in `dashboardPage()`, in `shinydashboard` title can be passed in `dashboardHeader()` function.
2. No `sidebarMenu()` function in `semantic.dashboard`
3. In `semantic.dashboard` we need to add `column()` surrounding `box`es and `valueBoxes`, in `shinydashboard` they have `width` argument
4.
