### ISSUE TITLE
Convert "simple sales revenue dashboard"

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/semantic.dashboard#29]
https://www.r-bloggers.com/building-a-simple-sales-revenue-dashboard-with-r-shiny-shinydashboard/

**Comment by maju116** [comment]
Differences in `ui.R` between `semantic.dashboard` and `shinydashboard` :

1. In `semantic.dashboard` title is passed in `dashboardPage()`, in `shinydashboard` title can be passed in `dashboardHeader()` function.
2. No `sidebarMenu()` function in `semantic.dashboard`
3. In `semantic.dashboard` we need to add `column()` surrounding `box`es and `valueBoxes`, in `shinydashboard` they have `width` argument
4. Alias for `uirender_value_box` not working
5. Box minimize is not working
6. We can't add links to menu items

**Comment by marekrogala** [comment]
@maju116 as discussed on meeting, let's fix `No sidebarMenu() function in semantic.dashboard` within this issue. For the rest, we can create separate followup issues.
