### ISSUE TITLE
Create a list of unimplemented functions from ShinyDashboard and differences in sygnatures

### ISSUE THREAD

**Issue by maju116** [Appsilon/semantic.dashboard#30]
Add unit tests for checking functions in sematcic.dashboard and shinydashboard.

Implemented from shinydashboard:

 box 
 sidebarMenu
 dashboardBody 
 dashboardHeader 
 dashboardPage 
 dashboardSidebar 
 menuItem 
 menuSubItem 
 renderValueBox 
 tabItem 
 tabItems 
 valueBox 
 valueBoxOutput
 dropdownMenu 
 dropdownMenuOutput 
 infoBox 
 infoBoxOutput 
 messageItem 
 notificationItem 
 renderDropdownMenu 
 renderInfoBox 
 tabBox
 taskItem 

Not implemented from shinydashboard:

 menuItemOutput 
 renderMenu  
 sidebarMenuOutput 
 sidebarSearchForm 
 sidebarUserPanel  
 updateTabItems 

Arguments:

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:left;"> fun </th>
   <th style="text-align:left;"> common </th>
   <th style="text-align:left;"> only_shiny </th>
   <th style="text-align:left;"> only_semantic </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> box </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ..., title, width, collapsible </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> footer, status, solidHeader, background, height, collapsed </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> color, ribbon, title_side </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> dashboardBody </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ... </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> dashboardHeader </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ..., disable </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> title, titleWidth, .list </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> color </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> dashboardPage </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> header, sidebar, body, title </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> skin </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> suppress_bootstrap </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> dashboardSidebar </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ..., disable </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> width, collapsed </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> side, size, color, center, visible </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> dropdownMenu </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ..., type, icon </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> badgeStatus, headerText, .list </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> dropdownMenuOutput </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> outputId </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> infoBox </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> value, subtitle, icon, color, width </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> title, href, fill </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> infoBoxOutput </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> outputId, width </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> menuItem </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> text, ..., icon, tabName, href, newtab </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> badgeLabel, badgeColor, selected, expandedName, startExpanded </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> menuSubItem </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> text, tabName, href, newtab, icon </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> selected </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ... </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> messageItem </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> from, message, icon </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> time, href </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> color </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> notificationItem </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> text, icon </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> status, href </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> color </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> renderDropdownMenu </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> expr, env, quoted </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> renderInfoBox </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> expr, env, quoted </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> renderValueBox </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> expr, env, quoted </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> sidebarMenu </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ... </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> id, .list </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> tabBox </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> title, width </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ..., id, selected, height, side </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> tabs, color, ribbon, title_side, collapsible </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> tabItem </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> tabName, ... </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> tabItems </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> ... </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> selected </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> taskItem </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> text, value, color </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> href </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> valueBox </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> value, subtitle, icon, color, width </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> href </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;font-weight: bold;color: white;background-color: #D7261E;"> valueBoxOutput </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;"> outputId, width </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
   <td style="text-align:left;width: 30em; font-weight: bold;color: white;background-color: #D7261E;">  </td>
  </tr>
</tbody>
</table>

**Comment by shahreyar-abeer** [comment]
Hi there,

So how should the updateTabItems function be implemented in semantic.dashboard.
