### ISSUE TITLE
Fix tab switching (suspendWhenHidden = FALSE)

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/semantic.dashboard#48]
I think it's best if you two @maju116 and @filipstachura discuss what we can do to fix tab switching
(so that we don't have to add `suspendWhenHidden = FALSE`)

**Comment by filipstachura** [comment]
We need to use `$(document).trigger("shown")` (or `"hidden"`). This works by finding all shiny outputs and sending info via websocket about new visible elements.

More info: https://groups.google.com/forum/#!topic/shiny-discuss/uw7MTYWG6Jw
