### ISSUE TITLE
Add `inverted` argument to both header and sidebar?

### ISSUE THREAD

**Issue by filipstachura** [Appsilon/semantic.dashboard#62]

**Comment by maju116** [comment]
Thanks to inverted in `"inverted menu sidebar"` we have colored all sidebar not only text. Look at the sidebar with setting `color = "blue"` with and without `inverted` class:

With `inverted` class:

![with_inverted](https://user-images.githubusercontent.com/11685462/34872859-f9628cbc-f792-11e7-80a1-0fb682901ef4.png)

Without `inverted` class:

![without_inverted](https://user-images.githubusercontent.com/11685462/34872874-07cd86e4-f793-11e7-9cc7-b5804a299034.png)

**Comment by filipstachura** [comment]
Got it. I feel that we should have an option for both of these.

Can I add `inverted = c(TRUE, FALSE)` argument to menu and sidebar? This way it would be possible to get both of these.

**Comment by maju116** [comment]
Yes, good idea
