### ISSUE TITLE
BUG: Tab content does not take up all width available.

### ISSUE THREAD

**Issue by DamianRodziewicz** [Appsilon/semantic.dashboard#74]
Space on the right of the sample boxes is empty whilst sample boxes should take up whole space.

![image](https://user-images.githubusercontent.com/4648934/34949562-bca82202-fa10-11e7-8357-4def10805249.png)

**Comment by filipstachura** [comment]
We need to make pusher content "flexible". It should expand when sidebar is hidden. Currently the content is being pushed.
