### ISSUE TITLE
BUG: Box should be collapsed by clicking on icon not by clicking on any place in label.

### ISSUE THREAD

**Issue by maju116** [Appsilon/semantic.dashboard#85]
I was trying to change JS code, but nothing was working (not even adding `id`)

**Comment by filipstachura** [comment]
@maju116  for future reference - things like this are in more than 90% cases described in Semantic documentation. In this case here: https://semantic-ui.com/modules/accordion.html#/examples

(Changing Trigger section)

**Comment by dokato** [comment]
Done
