### ISSUE TITLE
Feature request: add possibility to move cards.

### ISSUE THREAD

**Issue by filipstachura** [Appsilon/semantic.dashboard#9]
Inspired by cartodb dashboards: https://carto.com/blog/new-approach-customer-segmentation-location-data/

What possible we can use to implement this:
- http://rubaxa.github.io/Sortable/
- https://bevacqua.github.io/dragula/

**Comment by osenan** [comment]
@filipstachura is this something you still would like to include in `semantic.dashboard`? In my opinion this feature is very interesting but should not be part of `semantic.dashboard`, which is more about main ui components like headers, menu, sidebar... I would rather include it into another package.

**Comment by filipstachura** [comment]
@osenan Yes, I agree this belongs elsewhere. We can close this one.
